name: Docker Publish (GitHub Packages Docker registry)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-image:
    name: Build And Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set Variables
        run: |
          APPLICATION_NAME=${GITHUB_REPOSITORY,,} # convert repo name to lowercase
          REPOSITORY_NAME="${{ github.event.repository.name }}"
          RELEASE_VERSION=$(echo ${GITHUB_REF:10} | tr '[:upper:]' '[:lower:]')

          echo "::set-env name=APPLICATION_NAME::$APPLICATION_NAME"
          echo "::set-env name=REPOSITORY_NAME::$REPOSITORY_NAME"
          echo "::set-env name=RELEASE_VERSION::$RELEASE_VERSION"
          echo "::set-env name=DOCKER_REGISTRY::docker.pkg.github.com"

      # Requires v1 of this action for GitHub Packages Docker registry support
      - name: Build And Push Docker Image
        uses: docker/build-push-action@v1
        with:
          push: true
          repository: ${{ env.APPLICATION_NAME }}/${{ env.REPOSITORY_NAME }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}
          tags: ${{ env.RELEASE_VERSION }},latest
