name: Docker Security Scan

on:
  pull_request: ~
  schedule:
    - cron: '0 8 * * *' # Triggers daily at 800

jobs:
  build-and-trivy-scan:
    name: Build And Scan Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set Variables
        run: |
          APPLICATION_NAME=${GITHUB_REPOSITORY,,} # convert repo name to lowercase
          REPOSITORY_NAME=$(echo "${{ github.repository }}" | cut -d/ -f2 | tr '[:upper:]' '[:lower:]')

          echo "APPLICATION_NAME=$APPLICATION_NAME/$REPOSITORY_NAME" >> $GITHUB_ENV
          echo "DOCKER_REGISTRY=docker.pkg.github.com" >> $GITHUB_ENV
          echo "IMAGE_TAGS=latest" >> $GITHUB_ENV

      - name: Setup Docker Buildx To Load Image
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      # Requires v1 of this action for GitHub Packages Docker registry support
      - name: Build Docker Image
        uses: docker/build-push-action@v1
        with:
          push: false
          repository: ${{ env.APPLICATION_NAME }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}
          tags: ${{ env.IMAGE_TAGS }}

      - name: Scans Docker image with Trivy And Output As Table
        if: github.event_name == 'pull_request'
        uses: aquasecurity/trivy-action@0.0.8
        with:
          image-ref: ${{ env.DOCKER_REGISTRY }}/${{ env.APPLICATION_NAME }}:${{ env.IMAGE_TAGS }}
          ignore-unfixed: true
          exit-code: '1'
          severity: 'MEDIUM,HIGH,CRITICAL'

      - name: Scans Docker image with Trivy And Output As Template
        if: github.event_name == 'schedule'
        uses: aquasecurity/trivy-action@0.0.8
        with:
          image-ref: ${{ env.DOCKER_REGISTRY }}/${{ env.APPLICATION_NAME }}:${{ env.IMAGE_TAGS }}
          ignore-unfixed: true
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          exit-code: '1'
          severity: 'MEDIUM,HIGH,CRITICAL'

      # We don't have access to the security tab right now
#      - name: Upload Trivy Result To Security Tab
#        if: github.event_name == 'schedule'
#        uses: github/codeql-action/upload-sarif@v1
#        with:
#          sarif_file: 'trivy-results.sarif'
