name: Docker Image to GitHub Packages

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build + Publish Docker Image to GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Publish to GitHub Packages
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          # TODO - CHANGE ME!!!
          name: csun-it/REPO_NAME/PKG_NAME
          workdir: .
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: "latest,${{ env.RELEASE_VERSION }}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
