name: Docker Security Scan

on:
  pull_request: ~
  schedule:
    - cron: '0 8 * * *' # Triggers daily at 800

jobs:
  build-and-trivy-scan:
    name: Build And Scan Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set Variables
        run: |
          APPLICATION_NAME=${GITHUB_REPOSITORY,,} # convert repo name to lowercase
          RELEASE_VERSION='latest'

          echo "::set-env name=APPLICATION_NAME::$APPLICATION_NAME"
          echo "::set-env name=RELEASE_VERSION::$RELEASE_VERSION"
          echo "::set-env name=DOCKER_REGISTRY::docker.pkg.github.com"

      - name: Setup Docker Buildx To Load Image
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      - name: Build Docker Image Only
        uses: docker/build-push-action@v2
        with:
          load: true
          no-cache: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.APPLICATION_NAME }}:${{ env.RELEASE_VERSION }}

      - name: Scans Docker image with Trivy And Output As Table
        if: github.event_name == 'pull_request'
        uses: aquasecurity/trivy-action@0.0.8
        with:
          image-ref: ${{ env.DOCKER_REGISTRY }}/${{ env.APPLICATION_NAME }}:${{ env.RELEASE_VERSION }}
          ignore-unfixed: true
          exit-code: '1'
          severity: 'MEDIUM,HIGH,CRITICAL'

      - name: Scans Docker image with Trivy And Output As Template
        if: github.event_name == 'schedule'
        uses: aquasecurity/trivy-action@0.0.8
        with:
          image-ref: ${{ env.DOCKER_REGISTRY }}/${{ env.APPLICATION_NAME }}:${{ env.RELEASE_VERSION }}
          ignore-unfixed: true
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          exit-code: '0'
          severity: 'MEDIUM,HIGH,CRITICAL'

      - name: Upload Trivy Result To Security Tab
        if: github.event_name == 'schedule'
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
