name: DockerBuild

on:
  push:
    branches:
      - master
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-and-push-image:
    name: Build And Push Image
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set Variables
        run: |
          APPLICATION_NAME=${GITHUB_REPOSITORY,,}
          RELEASE_VERSION=$(echo $(echo ${GITHUB_REF:10} | tr '[:upper:]' '[:lower:]'))

          echo "::set-env name=APPLICATION_NAME::$APPLICATION_NAME"
          echo "::set-env name=RELEASE_VERSION::$RELEASE_VERSION"
          echo "::set-env name=DOCKER_REGISTRY::docker.pkg.github.com"

      - name: Setup Docker Buildx To Build And Upload Image
        uses: docker/setup-buildx-action@v1

      - name: Build And Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.APPLICATION_NAME }}:${{ env.RELEASE_VERSION }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.APPLICATION_NAME }}:latest
