name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: self-hosted

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SVC_K8S_DEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SVC_K8S_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Create Kubernetes Context
        run: aws eks update-kubeconfig --name projectkate-eks-cluster

      - name: Get Kubernetes Context
        id: get-kubeconfig
        run: |
          KUBECONFIG=$(cat $HOME/.kube/config)
          KUBECONFIG="${KUBECONFIG//'%'/'%25'}"
          KUBECONFIG="${KUBECONFIG//$'\n'/'%0A'}"
          KUBECONFIG="${KUBECONFIG//$'\r'/'%0D'}"
          echo "::set-output name=kubeconfig::$KUBECONFIG"

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ steps.get-kubeconfig.outputs.kubeconfig }}

      - name: Apply Manifest
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            # TODO - Path to the manifest file(s) to be used for deployment
            #        multiple files should be split by new lines
          namespace: # TODO - Kubernetes namespace to deploy to
